name: "Retention Science ECS Redploy Action for GitHub Actions"
description: "Forces redeployment for the given ECS service"
branding:
  icon: "cloud"
  color: "orange"
inputs:
  service:
    description: "The name of an ECS service."
    required: true
  cluster:
    description: "The name of an ECS cluster. (default: common-cluster)"
    required: false
  wait-for-minutes:
    description: "How long to wait for the deploy to become stable again. (default :30)"
    required: false
outputs:
  status:
    description: "Return status of ECS update command"
runs:
  using: "node12"
  main: "dist/index.js"
