name: "Retention Science ECS Redploy Action for GitHub Actions"
description: "Forces redeployment for the given ECS service"
branding:
  icon: "cloud"
  color: "orange"
inputs:
  service:
    description: "The name of an ECS service."
    required: true
  cluster:
    description: "The name of an ECS cluster."
    required: true
outputs:
  status:
    description: "Return status of ECS update command"
runs:
  using: "node12"
  main: "dist/index.js"
